# Generated by Django 2.1.7 on 2019-04-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddobaki', '0002_get_ddobaki_current_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post_ddobaki',
        ),
        migrations.AddField(
            model_name='get_ddobaki',
            name='color',
            field=models.CharField(default='2019-04-25T20:30:45.771952+09:00', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='get_ddobaki',
            name='divided_stt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
