# Generated by Django 2.1.7 on 2019-06-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddobaki', '0004_auto_20190430_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_ddobaki',
            name='accuracy',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='get_ddobaki',
            name='color',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
