# Generated by Django 2.1.7 on 2019-06-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddobaki', '0005_auto_20190622_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_ddobaki',
            name='accuracy',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
