# Generated by Django 2.1.7 on 2019-04-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddobaki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_ddobaki',
            name='current_time',
            field=models.DateTimeField(auto_now_add=True, default='2019-04-27 21:13:54.771952+09'),
            preserve_default=False,
        ),
    ]
