# Generated by Django 2.1.7 on 2019-04-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddobaki', '0003_auto_20190430_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_ddobaki',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='get_ddobaki',
            name='divided_stt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
