# Generated by Django 2.1.7 on 2019-10-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddobaki', '0008_auto_20190622_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='word_list1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
            ],
        ),
    ]
