# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod "MBCircularProgressBar"
pod 'Alamofire', '~> 4.7' 
# Pods for Test3

end
